[workspace]
channels = ["conda-forge"]
name = "cuda-exercise"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.7.1,<3"
python = ">=3.12.11,<3.14"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

[feature.cpu.dependencies]
pytorch-cpu = "*"

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"
