[workspace]
channels = ["conda-forge"]
name = "htcondor"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.11,<3.14"

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.gpu.system-requirements]
cuda = "11.8"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = "*"
torchvision = "*"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
