[workspace]
channels = ["conda-forge"]
name = "htcondor"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[feature.cpu.dependencies]
python = ">=3.13.5,<3.14"
pytorch-cpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.gpu.system-requirements]
cuda = "11.8"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.5.1,<3"
torchvision = ">=0.20.1,<0.21.0"
cuda-version = "11.8.*"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]
