[workspace]
authors = ["David Webber <david@scanalyticsinc.com>"]
channels = ["conda-forge"]
name = "htcondor"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[environments]
cpu = ["cpu"]
gpu = ["gpu"]

[feature.cpu.dependencies]
pytorch-cpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.gpu.dependencies]
torchvision = "*"

[feature.gpu.system-requirements]
cuda = "12.9"

[feature.gpu.target.linux-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"

[feature.gpu.target.win-64.dependencies]
pytorch-gpu = ">=2.7.1,<3"
torchvision = ">=0.22.0,<0.23"
